name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: run_action
      with:
        key: "keyB"
        map: |
          {
            "keyA": {
              "env1A": "value1A",
              "env2A": "value2A",
              "env3A": "value3A"
            },
            "...B": {
              "env1B": "value1B",
              "env2B": "value2B",
              "env3B": "value3B"
            },
            ".*": {
              "env1C": "value1C",
              "env2C": "value2C",
              "env3C": "value3C"
            }
          }
        export_to: log,env,output
    - name: 'Test Actions Parameters'
      run: |
        test "${{env.env1B}}" = "value1B"
        test "${{env.env2B}}" = "value2B"
        test "${{env.env3B}}" = "value3B"
        test "${{steps.run_action.outputs.env1B}}" = "value1B"
        test "${{steps.run_action.outputs.env2B}}" = "value2B"
        test "${{steps.run_action.outputs.env3B}}" = "value3B"
  
  test-readme-example1:
    runs-on: ubuntu-latest
    steps:
    # chris-madsen/variable-mapper@v0.1.2
    - uses: ./
      with:
        key: "${{ github.base_ref }}"
        map: |
          {
            "master": {
              "environment": "prod",
              "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID_001",
              "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY_002"
            },
            "qa": {
              "environment": "qa",
              "AWS_ACCESS_KEY_ID": "hash1",
              "AWS_SECRET_ACCESS_KEY": "hash2"
            },
            "development": {
              "environment": "dev,
              "AWS_ACCESS_KEY_ID": "hash3",
              "AWS_SECRET_ACCESS_KEY": "hash4"
            }
          }
        export_to: env
    - name: Echo environment
      run: echo ${{ env.environment }}
      
