name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: run_action
      with:
        key: "keyB"
        map: |
          {
            "keyA": {
              "env1A": "value1A",
              "env2A": "value2A",
              "env3A": "value3A"
            },
            "...B": {
              "env1B": "value1B",
              "env2B": "value2B",
              "env3B": "value3B"
            },
            ".*": {
              "env1C": "value1C",
              "env2C": "value2C",
              "env3C": "value3C"
            }
          }
        export_to: log,env,output
    - name: 'Test Actions Parameters'
      run: |
        test "${{env.env1B}}" = "value1B"
        test "${{env.env2B}}" = "value2B"
        test "${{env.env3B}}" = "value3B"
        test "${{steps.run_action.outputs.env1B}}" = "value1B"
        test "${{steps.run_action.outputs.env2B}}" = "value2B"
        test "${{steps.run_action.outputs.env3B}}" = "value3B"
  example: # Test README use case
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: run_action
      with:
        key: "${{ github.event_name }}"
        map: |
          {
            "push|pull_request": {
              "example": "${{secrets.EXAMPLE}}"
            }
          }
        export_to: env
    - name: 'Test Actions Parameters'
      run: |
        test "${{env.example}}" = "example"
  test-readme-example1:
    runs-on: ubuntu-latest
    steps:
    - uses: chris-madsen/variable-mapper@v0.1.2
      with:
        key: "${{github.base_ref}}"
        map: |
          {
            "master": {
              "environment": "production",
              "AWS_ACCESS_KEY_ID": "${{ secrets.PROD_AWS_ACCESS_KEY_ID }}",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.PROD_AWS_ACCESS_KEY_ID }}"
            },
            "staging": {
              "environment": "staging",
              "AWS_ACCESS_KEY_ID": "${{ secrets.STG_AWS_ACCESS_KEY_ID }}",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.STG_AWS_ACCESS_KEY_ID }}"
            },
            ".*": {
              "environment": "development",
              "AWS_ACCESS_KEY_ID": "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}"
            }
          }
    - name: Echo environment
      run: echo ${{ env.environment }}
  test-readme-example2:
    runs-on: ubuntu-latest
    steps:
    - uses: chris-madsen/variable-mapper@v0.1.2
      id: export
      with:
        key: "${{github.base_ref}}"
        map: |
          {
            "master": {
              "environment": "production"
            },
            ".*": {
              "environment": "development"
            }
          }
        export_to: env,log,output
    - name: Echo environment and output
      run: |
        echo ${{ env.environment }}
        echo ${{ steps.export.outputs.environment }}
